### ISSUE TITLE
Certificate of `www.kermeta.org` has expired, thus, breaking the Eclipse update site

### ISSUE THREAD

**Issue by maxkratz** [diverse-project/k3#106]
The certificate of https://www.kermeta.org has expired on April, 5th of 2024.
This breaks the Eclipse update site: https://www.kermeta.org/k3/update/

`openssl` confirms the expired certificate:

```
$ openssl s_client -connect www.kermeta.org:443 < /dev/null | openssl x509 -noout -text                  
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = NL, O = GEANT Vereniging, CN = GEANT OV RSA CA 4
verify return:1
depth=0 C = FR, ST = \C3\8Ele-de-France, O = INSTITUT NATIONAL DE RECHERCHE EN INFORMATIQUE ET EN AUTOMATIQUE, CN = www.kermeta.org
verify error:num=10:certificate has expired
notAfter=Apr  5 23:59:59 2024 GMT
verify return:1
depth=0 C = FR, ST = \C3\8Ele-de-France, O = INSTITUT NATIONAL DE RECHERCHE EN INFORMATIQUE ET EN AUTOMATIQUE, CN = www.kermeta.org
notAfter=Apr  5 23:59:59 2024 GMT
verify return:1
DONE
```

**Comment by dvojtise** [comment]
apparently I cannot renew the certificate myself, I've opened a ticket in our SI.

I expect it to be solved next week


BTW,  to avoid such annoying compilation issue in the future, I should consider moving the update site(s) to another host (for example on github.io) for all our projects (k3, but also melange, ale-lang, etc :cry: )

**Comment by maxkratz** [comment]
> apparently I cannot renew the certificte myself, I've opened a ticket in our SI.
> 
> I expect it to be solved next week

Thanks for the update :).

> BTW, to avoid such annoying compilation issue in the future, I should consider moving the update site(s) to another host (for example on github.io) for all our projects (k3, but also melange, etc 😢 )

You are right, that would be one way to deal with it.

**Comment by maxkratz** [comment]
As far as I can see, there is a new (valid) certificate in place:

```
depth=0 C = FR, ST = Yvelines, O = INSTITUT NATIONAL DE RECHERCHE EN INFORMATIQUE ET EN AUTOMATIQUE, CN = www.kermeta.org
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = FR, ST = Yvelines, O = INSTITUT NATIONAL DE RECHERCHE EN INFORMATIQUE ET EN AUTOMATIQUE, CN = www.kermeta.org
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 C = FR, ST = Yvelines, O = INSTITUT NATIONAL DE RECHERCHE EN INFORMATIQUE ET EN AUTOMATIQUE, CN = www.kermeta.org
verify return:1
DONE
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            99:a7:a2:a5:04:c2:d4:68:61:4b:f8:3c:53:f7:df:c0
        Signature Algorithm: sha384WithRSAEncryption
        Issuer: C = NL, O = GEANT Vereniging, CN = GEANT OV RSA CA 4
        Validity
            Not Before: Apr 18 00:00:00 2024 GMT
            Not After : Apr 18 23:59:59 2025 GMT
```

This resolves the issue.

**Comment by dvojtise** [comment]
yes, this was done this morning (you were quicker to check than me to notify you ;-)  )
