### ISSUE TITLE
[HIGH] Generate the eclipse extension "generated_package"

### ISSUE THREAD

**Issue by tongbong** [diverse-project/k3#29]
K3SLE generates the extended MM and its genmodel.
The user is responsible for generating the java code.
In a normal Ecore/EMF usage, the code generation also specifies the eclipse extension as followed:
   <extension
         point="org.eclipse.emf.ecore.generated_package">
      <package
            class="sigpmlextended.SigpmlextendedPackage"
            genModel="model/SigPMLExtended.genmodel"
            uri="http://org.gemoc.sigpml.model/1.0/extended">
      </package>
   </extension>

But when using K3SLE, that extension is not generated, thus forcing the user to do it by hand.
Something has to be missing in the genmodel.

**Comment by dvojtise** [comment]
This isn't the role of K3 anymore, this is now part of Melange and As far as I know it takes care of that
