### ISSUE TITLE
Memory leak on aspects

### ISSUE THREAD

**Issue by dvojtise** [diverse-project/k3#32]
The current implementation of k3 aspect uses a simple HashMap (see XXXAspectContext)
this is the source of a huge memory leak. Neither the base object nor the companion XXXAspectProperties object can be garbage collected.

**Comment by fcoulon** [comment]
Maybe we can solve this with weak references

https://weblogs.java.net/blog/2006/05/04/understanding-weak-references

**Comment by dvojtise** [comment]
yes, indeed. I've already used such strategy in Kermeta 1 in order to solve similar issue.
Another alternative is to look for a dedicated library in apache commons or guava (typically cache implementations which will use the weak references internally)
