### ISSUE TITLE
Thread safety vulnerability 

### ISSUE THREAD

**Issue by dvojtise** [diverse-project/k3#34]
The current implementation uses a static property in order to store the companion XXXAspectProperties object for a given XXX object. 
This leads to potentiel issues when the same K3 code is executed in a multithreading environment. For exemple: apply the same trasnformation on 2 models in eclipse. (or if 2 differents transformations reuses the same aspects)

It would be much better to be able to pass the companion XXXAspectProperties object as a parameter of the method.

Ex of code with the pb
xtedn code:
```
class AA {
	public var String name
}
@Aspect(className=AA) 
class AspectA {  	 
 	 var String qualifiedName  
	def void initializer(){ 
		println("initializer of AspectA on AA")
		_self.qualifiedName = _self.name  
	}
}
```
currently generate the following code : 
```
@Aspect(className = AA.class)
@SuppressWarnings("all")
public class AspectA {

  @AspectInitializerMethod
  public static void initializer(final AA _self) {
    _self_ = test.constructor.AspectAAAAspectContext.getSelf(_self);
    _privk3_initializer(_self);
  }
  
  public static AspectAAAAspectProperties _self_;
  
  public static String qualifiedName(final AA _self) {
    _self_ = test.constructor.AspectAAAAspectContext.getSelf(_self);
    Object result = null;
    result =_privk3_qualifiedName(_self);
    return (java.lang.String)result;
  }
  
  public static void qualifiedName(final AA _self, final String qualifiedName) {
    _self_ = test.constructor.AspectAAAAspectContext.getSelf(_self);
    _privk3_qualifiedName(_self,qualifiedName);
  }
  
  protected static void _privk3_initializer(final AA _self) {
    InputOutput.<String>println("initializer of AspectA on AA");
    AspectA.qualifiedName(_self, _self.name);
  }
  
  protected static String _privk3_qualifiedName(final AA _self) {
     return test.constructor.AspectA._self_.qualifiedName; 
  }
  
  protected static void _privk3_qualifiedName(final AA _self, final String qualifiedName) {
    test.constructor.AspectA._self_.qualifiedName = qualifiedName; try {
    
    			for (java.lang.reflect.Method m : _self.getClass().getMethods()) {
    				if (m.getName().equals("set" + "QualifiedName")
    						&& m.getParameterTypes().length == 1) {
    					m.invoke(_self, qualifiedName);
    
    				}
    			}
    		} catch (Exception e) {
    			// Chut !
    		} 
  }
```

the problem is the use of "_self_" as a static property instead of a method parameter when qualifiedName() call _privk3_qualifiedName

**Comment by arnobl** [comment]
Why not writing:
synchronized(_self) {

}

in this aspects?

**Comment by dvojtise** [comment]
synchronizing on a single base object will not be enough. 
If we consider the approach using synchronization we need to use the static property _ self _ as lock, this property is not visible from xtend code.
(And I'm not speaking about the performance slowdown ...)

**Comment by dvojtise** [comment]
additionnaly the use of this static property is a potentiel memory leak. (smaller than bug  #32) 
indeed, the last aspectized class will never be garbage collected (with all its dependencies in the model graph)
