### ISSUE TITLE
How to run a single application in K3

### ISSUE THREAD

**Issue by valdemarneto** [diverse-project/k3#39]
Hi all.

My name is Valdemar. I am member of the ArchWARE group in UBS à Vannes.

I am starting at work with K3, but I am having a lot of difficulties about running even one single application.

I am using the examples and tutorials provided here, but things are not running as expected.

I downloaded GEMOC and tried to use K3 examples are provided there. The dependency management is  "Plug-in", I checked the "Use EMF", and I am using the "Mini Aspect Sample".

However, the project is not really "done". It is necessary to build the path, including Xtend and K3 libraries manually, and even with that, some errors persist, like:

1. "the method or field _self is undefined for the type SampleXMLFileAspect"
2. "Aspect can not be solved as an annotation type"
3. fr.inria.diverse.k3.al.annotationprocessor.Aspect can not be solved to a type

I downloaded all the projects available here, and tried to import as library, or plugin, or other options, and it did not finish the errors. I imported thek3.al.annotationprocessor project (.eclipse, as recommended) for a empty project in Eclipse, but even did not work.

Any one has any suggestion of a tutorial or actions I should take to solve those problems and have a clean and functional initial example application running?

Thank you since now.

Regards,
Valdemar.

**Comment by dvojtise** [comment]
hi 
I just downloaded a Gemoc studio (2.0.0-SNAPSHOT) from http://gemoc.org/studio-download/
then File > new > Project > K3 project, 
next
Mini Aspect Sample


then add the missing "public" keyword for contentType and contentArrayList in SampleXMLFileAspect.xtend

this compiles correctly and run with a rigth click on the SampleMain.xtend , run as java application

(I'm using windows 7 + java 8 )

**Comment by valdemarneto** [comment]
Hi.

Thank you very much for the help. I think I was using an old version. It worked.

Regards,
Valdemar.
