### ISSUE TITLE
Problems when definining XDSML

### ISSUE THREAD

**Issue by valdemarneto** [diverse-project/k3#41]
Hi. 

I am starting a new project of concurrent language.
I defined by language using XText and extracted the Ecore model from it.
I created the XDSML file, and selected the EMF Project, the GenModel URI.
However, when I choose the GenModel URI, the project.xdsml automatically changes, and I am not able to create a K3 or MoCCML project anymore. This is what appears:

![image](https://cloud.githubusercontent.com/assets/8572569/13109603/99899a42-d57a-11e5-83b7-3f09b433c9b2.png)

I use GEMOC 1.0 in Windows.
Why does it happen?

It looks like this happen because I defined my language based in XText and non directly from Ecore. When I try to generate the codes referent to the language, they are created in other projects, with xtext in the name instead of being created in the same project of the model.

Thank you since now.

**Comment by dvojtise** [comment]
Hi may be you just have to open the main tab in the XDSML editor (it seems on your scrennshot that you have switched to the XDSML custom tab)
![99899a42-d57a-11e5-83b7-3f09b433c9b2](https://cloud.githubusercontent.com/assets/661468/13110143/7c98fc12-d57e-11e5-93d4-587d41ebe392.png)

**Comment by dvojtise** [comment]
This issue was moved to gemoc/gemoc-studio#2
