### ISSUE TITLE
Unkown or deprecated use of PreCondition annotation

### ISSUE THREAD

**Issue by dvojtise** [diverse-project/k3#59]
In the aspect processor there is an annotation 

```xtend
@Target(ElementType.TYPE_USE)
public annotation PreCondition {
}
```
https://github.com/diverse-project/k3/blob/d69e5ebf5602a30bc21cd606f0f50ded571a1fd2/k3.eclipse/fr.inria.diverse.k3.al.annotationprocessor.plugin/src/fr/inria/diverse/k3/al/annotationprocessor/Aspect.xtend#L47

does someone knows it usage ?

@d-leroy  you seem to be the author for this, do you still use it ? otherwise can you add some documentation (javadoc + memento)  https://github.com/diverse-project/k3/blob/gh-pages/documentation_src/user_documentation/src/main/asciidoc/memento.asciidoc

**Comment by d-leroy** [comment]
This annotation is not used anymore and can be deleted.
