### ISSUE TITLE
Not all dependencies packed (?)

### ISSUE THREAD

**Issue by lmouline** [diverse-project/k3#67]
When I try to install K3 plugin using the update site, I get the following "error":
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: K3 feature 3.2.3.v20180905-1556 (fr.inria.diverse.k3.feature.feature.group 3.2.3.v20180905-1556)
  Missing requirement: K3 UI 3.2.3.v20180905-1556 (fr.inria.diverse.k3.ui 3.2.3.v20180905-1556) requires 'osgi.bundle; org.eclipse.gemoc.commons.eclipse.pde 1.0.0' but it could not be found
  Cannot satisfy dependency:
    From: K3 feature 3.2.3.v20180905-1556 (fr.inria.diverse.k3.feature.feature.group 3.2.3.v20180905-1556)
    To: org.eclipse.equinox.p2.iu; fr.inria.diverse.k3.ui [3.2.3.v20180905-1556,3.2.3.v20180905-1556]
```

It asks me to install manually a Gemoc package: `org.eclipse.gemoc.commons.eclipse.pde`.

I don't really know if it's an error or a good practice for plugin packaging.

**Comment by lmouline** [comment]
Yep I did this :)
Thanks

**Comment by dvojtise** [comment]
actually, even when k3 was dependent on diverse-commons (before its port to gemoc commons) the diverse commons stuff were not distributed in K3 update site.

However you're right, we can easily add it for simpler installation


BTW, the official update site for gemoc is one of those here: http://download.eclipse.org/gemoc/updates/?d

**Comment by lmouline** [comment]
OK :)

Many thanks
