### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [diverse-project/k3#71]
Hello Kermeta3 team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Kermeta3 project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by dvojtise** [comment]
Hii thanks for offering use the opportunity to highlight our project in the xtend community

here are the required informations:

```
<tr>
	<td><a href="kermeta.org/">Kermeta 3</a></td>
	<td>K3 is an extension of Xtend programming language. It allows to "re-open" the classes generated from an Ecore metamodel using annotations in order to weave new features and operations.</td>
	<td>EPL</td>
	<td>Language</td>
	<td>Inria/IRISA</td>
</tr>

```

**Comment by miklossy** [comment]
Thank you @dvojtise !

**Comment by miklossy** [comment]
The `Kermeta 3` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
